name: Automatic test on Push
on: push

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Renaming JAR file
        run: mv target/*-SNAPSHOT.jar target/app.jar
      - name: Run on BG
        run: |
          java -jar target/app.jar --server.port=8888 &
          echo $! > app.pid
      - uses: matt-ball/newman-action@master
        with:
          collection: test.postman_collection
          environment: test.postman_environment
